controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

use app\models\Book\Books;
use app\models\Book\BookForm;
use app\models\Book\BookSearch;
use app\models\UploadForm;

use app\models\Category\BookCategory;

use yii\web\UploadedFile;

use app\components\TraitComponent;

class BookController extends Controller
{
  public function actionIndex()
  {
    $books = new BookSearch();
    // 用url參數來查詢資料
    $dataProvider = $books->search(Yii::$app->request->queryParams);
    Yii::info('開啟Borrow Index'.json_encode($dataProvider));
    return $this->render('index', [
        'book' => $books,
        'dataProvider' => $dataProvider,
    ]);
  }

  public function actionCreate()
  {
    $model = new Books();
    
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      Yii::$app->session->setFlash('success', "新增成功");
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('create', ['model'=> $model]);
    }
  }

  public function actionBorrow()
  {
    $model = new Books();
    
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      $uploadModel = new UploadForm();
      if ($uploadModel->upload()) {
          // 文件上传成功
          return $this->redirect(['view', 'id' => $model->id]);
      }
    } else {
      return $this->render('borrow', ['model'=> $model]);
    }
  }

  public function actionUpdate($id)
  {
    $model = $this->findModel($id);

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      $uploadModel = new UploadForm();
      // var_dump(UploadedFile::getInstances($model, 'imageFile'));
      // 從model取得檔案上傳的資料設定到屬性
      $uploadModel->imageFile = UploadedFile::getInstances($model, 'imageFile');
      if ($uploadModel->upload()) {
          // 文件上传成功
          return $this->redirect(['view', 'id' => $model->id]);
      }
      Yii::$app->session->setFlash('success', "更新成功");
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('update', ['model'=> $model]);
    }
  }

  public function actionDelete($id)
  {
    $this->findModel($id)->delete();
    Yii::$app->session->setFlash('success', "刪除成功");
    return $this->redirect(['index']);
  }

  public function actionView($id)
  {
    return $this->render('view',[
      'model' => $this->findModel($id),
    ]);
  }

  public function findModel($id)
  {
    if( ($model = Books::findOne($id)) != null) {
      return $model;
    } else {
      throw new NoFoundHttpException("找不到請求的頁面");
    }
  }

  // 暫不使用
  public function actionNewCategory()
  {
    $model = new BookCategory();
    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      return $this->redirect(['view', 'id' => $model->id]);
    } else {
      return $this->render('newcategory', ['model'=> $model]);
    }
  }
}

controllers/UserController.php
<?php
namespace app\controllers;

use Yii;

use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
* UserController implements the CRUD actions for User model.
*/
class UserController extends Controller
{
   /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
      return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['logout'],
              'rules' => [
                  [
                      'actions' => ['logout'],
                      'allow' => true,
                      'roles' => ['@'],
                  ],
              ],
          ],
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'logout' => ['post'],
              ],
          ],
      ];
  }

  public function actionIndex()
  {
    $title = "會員列表";
    return $this->render('index', ['title'=>$title]);
  }

  public function actionCreate()
  {
    $title = "新增會員";
    
    return $this->render('create', ['title'=>$title]);
  }

  public function actionUpdate($id)
  {
    $title = "修改會員";
    
    return $this->render('update', ['title'=>$title]);
  }
}

views/layouts/_msg.php
// display success message
<?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-success alert-dismissable">
         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
         <h4><i class="icon fa fa-check"></i>Saved!</h4>
         <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>

// display error message
<?php if (Yii::$app->session->hasFlash('error')): ?>
    <div class="alert alert-danger alert-dismissable">
         <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
         <h4><i class="icon fa fa-check"></i>Saved!</h4>
         <?= Yii::$app->session->getFlash('error') ?>
    </div>
<?php endif; ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

// AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Book', 'url' => ['/book/index']],
            ['label' => 'User', 'url' => ['/user/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>